#!/usr/bin/env bash

#ddev-generated
# Remove the line above if you don't want this file to be overwritten
# when you run ddev get julienloizelet/ddev-tools

## Description: Reload VCL config
## Usage: reload-vcl
## Example: "ddev reload-vcl"


HANDLE=varnish-cfg-$RANDOM ; \
  varnishadm vcl.load $HANDLE /etc/varnish/default.vcl && \
  varnishadm vcl.use $HANDLE
