#!/usr/bin/env bash

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-tools"

## Description: Replace ACL with some IP
## Usage: replace-acl IP
## Example: "ddev replace-acl 172.21.0.12"


sed -i -e "s/\".*\";\/\/REPLACE_WITH_SOME_IP$/\"$@\";\/\/REPLACE_WITH_SOME_IP/g" /etc/varnish/default.vcl
