#!/usr/bin/env bash

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-tools"

## Description: Run Magento 2 cron on every minute
## Usage: cron command
## Example: "ddev cron"

while true
do
  {
    echo "Start: $(date -u)"
    /usr/bin/php /var/www/html/bin/magento cron:run
    echo "End: $(date -u)"
  } >> /var/www/html/var/log/magento.cron.log
  sleep 60
done
