#!/usr/bin/env bash

#ddev-generated
# Remove the line above if you don't want this file to be overwritten
# when you run ddev get julienloizelet/ddev-tools

## Description: Run PHPCS for some folder
## Usage: phpcs folder
## Example: "ddev phpcs my-own-modules/my-module --ignore="*/node_modules/*""


/usr/bin/php ./vendor/bin/phpcs  --standard=Magento2 --extensions=php,phtml --error-severity=10 --ignore-annotations "$@"
