#!/usr/bin/env bash

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-tools"

## Description: Run PHPCS for some folder
## Usage: phpcs folder
## Example: "ddev phpcs my-own-modules/my-module --ignore="*/node_modules/*""


/usr/bin/php ./vendor/bin/phpcs  --standard=Magento2 --extensions=php,phtml --error-severity=10 "$@"
