#!/usr/bin/env bash

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-tools"

## Description: Run PHPCBF for some folder
## Usage: phpcbf folder
## Example: "ddev phpcbf my-own-modules/my-module"


/usr/bin/php ./vendor/bin/phpcbf  --standard=Magento2  "$@"
