#!/usr/bin/env bash

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-tools"

## Description: Run PHPMD for some folder
## Usage: phpmd folder
## Example: "ddev phpmd --exclude "node_modules" my-own-modules/my-module"


/usr/bin/php ./vendor/bin/phpmd  "$@" text dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml
