#!/usr/bin/env bash

#ddev-generated
# Remove the line above if you don't want this file to be overwritten
# when you run ddev get julienloizelet/ddev-tools

## Description: Run PHPMD for some folder
## Usage: phpmd folder
## Example: "ddev phpmd --exclude "node_modules" my-own-modules/my-module"


/usr/bin/php ./vendor/bin/phpmd  "$@" text dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml
