#!/usr/bin/env bash

#ddev-generated
# Remove the line above if you don't want this file to be overwritten
# when you run ddev get julienloizelet/ddev-tools

## Description: Run PHP UNIT test for some folder
## Usage: phpunit folder
## Example: "ddev phpunit my-own-modules/my-module/Test/Unit"

/usr/bin/php vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist "$@"
