#!/usr/bin/env bash

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-tools"

## Description: Run PHP UNIT test for some folder
## Usage: phpunit folder
## Example: "ddev phpunit my-own-modules/my-module/Test/Unit"

/usr/bin/php vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist "$@"
