#!/usr/bin/env bash

## Description: Run PHPCS for some folder
## Usage: phpcs bin_source folder standard
## Example: "ddev phpcs ./my-own-modules/my-module/vendor/bin/phpcs my-own-modules/my-module PSR2"


PHPCS_SOURCE=${1:-./}
MODULE_SOURCE=${2:-my-own-modules/my-module}
STANDARD=${3:-PSR12}

/usr/bin/php $PHPCS_SOURCE/vendor/bin/phpcs  --standard=$STANDARD $MODULE_SOURCE
