#!/usr/bin/env bash

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-tools"

## Description: Run PHPCBF for some folder
## Usage: phpcbf bin_source folder
## Example: "ddev phpcbf ./my-own-modules/my-module/vendor/bin/phpcbf my-own-modules/my-module PSR2"

PHPCBF_SOURCE=${1:-./}
MODULE_SOURCE=${2:-my-own-modules/my-module}
STANDARD=${3:-PSR12}

/usr/bin/php $PHPCBF_SOURCE/vendor/bin/phpcbf --standard=$STANDARD $MODULE_SOURCE
