#!/usr/bin/env bash

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-tools"

## Description: Run PHPMD for some folder
## Usage: phpmd root_folder ruleset_path code_folder
## Example: "ddev phpmd ./my-own-modules/crowdsec-php-lib tools/phpmd/rulesets.xml src"

ROOT=${1:-.}
RULESET_PATH=${2:-ruleset.xml}
MODULE_SOURCE=${3:-src}
FORMAT=${4:-text}


/usr/bin/php $ROOT/vendor/bin/phpmd  $ROOT/$MODULE_SOURCE $FORMAT $ROOT/$RULESET_PATH
