#!/usr/bin/env bash
#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run ddev get
## Description: Run PSALM for some folder
## Usage: psalm source config_source
## Example: "ddev psalm ./my-own-modules/my-module/ ./my-own-modules/my-module/psalm"


PSALM_SOURCE=${1:-./}
CONFIG_SOURCE=${2:-}

/usr/bin/php $PSALM_SOURCE/vendor/bin/psalm  --root=$CONFIG_SOURCE  --show-info=true
