#!/usr/bin/env bash

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-tools"

## Description: Run PSALM for some folder
## Usage: psalm source config_source
## Example: "ddev psalm ./my-own-modules/my-module/ ./my-own-modules/my-module/psalm"


PSALM_SOURCE=${1:-./}
CONFIG_SOURCE=${2:-}

/usr/bin/php "$PSALM_SOURCE"/vendor/bin/psalm  --root="$CONFIG_SOURCE"  --show-info=true
